
language: generic
sudo: false

matrix:
    include:

         # flake8
        - os: linux
          env: TEST_DEPS="flake8"
               PYTHON_VERSION="2.7"
               PYTHON_ARCH="64"
               TEST_RUN="style"

        # python 2.7; install from sdist
        - os: linux
          env: TEST_DEPS="numpy pandas pytables scikit-learn nose"
               PYTHON_VERSION="2.7"
               PYTHON_ARCH="64"
               TEST_RUN="sdist"

        # python 3.5; install from sdist
        - os: linux
          env: TEST_DEPS="numpy pandas pytables scikit-learn nose"
               PYTHON_VERSION="3.5"
               PYTHON_ARCH="64"
               TEST_RUN="sdist"

        # python 3.6
        - os: linux
          env: TEST_DEPS="numpy pandas pytables scikit-learn nose"
               PYTHON_VERSION="3.6"
               PYTHON_ARCH="64"

before_install:
    - uname -a
    - source "ci/travis/conda_setup.sh"

install:
    - source "ci/travis/conda_install.sh"

script:
    - source "ci/travis/numerox_setup.sh"

notifications:
    email:
        on_success: never
        on_failure: always
